---
# tasks for ansible_os_family == 'Debian'


# Manage Apt proxy
- name: Install Apt proxy configuration
  tags: silpion
  sudo: yes
  when: silpion_apt_proxy_enable == true
  template:
    src=apt.proxy.conf.j2
    dest=/etc/apt/apt.conf.d/proxy.conf
    owner=0
    group=0
    mode=0644

- name: Uninstall Apt proxy configuration
  tags: silpion
  sudo: yes
  when: silpion_apt_proxy_enable == false
  file:
    state=absent
    dest=/etc/apt/apt.conf.d/proxy.conf


# Manage Apt unattended automatic upgrades
- name: Configure Apt automatic upgrades
  tags: silpion
  sudo: yes
  template:
    src=apt.autoupgrades.conf.j2
    dest={{ silpion_apt_autoupgrades_cfg_file }}


# Manage package installation/removal
- name: Update apt package cache
  tags: silpion
  sudo: yes
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install requested packages
  tags: silpion
  sudo: yes
  with_flattened:
    - silpion_package_list_in
    - silpion_package_list_in_custom
  apt:
    state=installed
    name={{ item }}
    install_recommends=false
    dpkg_options='force-confold'

- name: Remove unwanted packages
  tags: silpion
  sudo: yes
  with_flattened:
    - silpion_package_list_out
    - silpion_package_list_out_custom
  apt:
    state=absent
    name={{ item }}
    purge=yes
    force=yes


# Misc system configuration
- name: Configure vim as default editor
  tags: silpion
  sudo: yes
  alternatives:
    link=/etc/alternatives/editor
    name=editor
    path=/usr/bin/vim.basic
