---
# tasks for ansible_os_family == 'Debian'


# Manage Apt proxy
- name: Install Apt proxy configuration
  tags: silpion
  when: silpion_apt_proxy_enabled == true
  template:
    src=apt.proxy.conf.j2
    dest=/etc/apt/apt.conf.d/proxy.conf
    owner=0
    group=0
    mode=0644

- name: Uninstall Apt proxy configuration
  tags: silpion
  when: silpion_apt_proxy_enabled == false
  file:
    state=absent
    dest=/etc/apt/apt.conf.d/proxy.conf


# Manage package installation/removal
- name: Update apt package cache
  tags: silpion
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install required packages
  tags: silpion
  with_flattened:
    - silpion_package_list_in
    - silpion_package_list_in_custom
  apt:
    state=installed
    name={{ item }}
    install_recommends=false
    dpkg_options='force-confold'

- name: Remove unwanted packages
  tags: silpion
  with_flattened:
    - silpion_package_list_out
    - silpion_package_list_out_custom
  apt:
    state=absent
    name={{ item }}
    purge=yes
    force=yes


# Misc system configuration
- name: Configure vim as default editor
  tags: silpion
  alternatives:
    link=/etc/alternatives/editor
    name=editor
    path=/usr/bin/vim.basic
