#!/bin/sh

: ${CMD_PYTHON:=python2}

read -s -p "Enter password: " PASSWD
echo
$CMD_PYTHON -c "from passlib.hash import sha512_crypt; print(sha512_crypt.encrypt('${PASSWD}'))"


# vim: set ft=sh ts=2 sw=2 et:
